projectDescription=FFMpeg4j is a lightweight Java library that provides a clean, fluent builder API for interacting with the ffmpeg and ffprobe command-line tools.
projectRepository=https://github.com/anisekai-project/ffmpeg4j

developerId=alexpado
developerName=Alexandre PADOVAN
developerEmail=contact@alexpado.fr
